name: Get AWS account

on:
  workflow_call:
    inputs:
      NODE_ENV:
        type: string
        required: true
    outputs:
      AWS_ACCOUNT:
        description: "aws account number"
        value: ${{ jobs.do.outputs.AWS_ACCOUNT }}
jobs:
  do:
    runs-on: self-hosted
    outputs:
      AWS_ACCOUNT: ${{ steps.beta.outputs.AWS_ACCOUNT || steps.gamma.outputs.AWS_ACCOUNT || steps.prod.outputs.AWS_ACCOUNT }}
    steps:
      - name: Get AWS_ACCOUNT
        id: beta
        if: inputs.NODE_ENV == 'beta' || inputs.NODE_ENV == 'dev'
        run: |
          echo "AWS_ACCOUNT=`echo ${{ secrets.AWS_ACCOUNT_BETA }} | base64`" >> $GITHUB_OUTPUT
      - name: Get AWS_ACCOUNT
        id: gamma
        if: inputs.NODE_ENV == 'gamma'
        run: |
          echo "AWS_ACCOUNT=`echo ${{ secrets.AWS_ACCOUNT_GAMMA }} | base64`" >> $GITHUB_OUTPUT
      - name: Get AWS_ACCOUNT
        id: prod
        if: inputs.NODE_ENV == 'prod'
        run: |
          echo "AWS_ACCOUNT=`echo ${{ secrets.AWS_ACCOUNT_PROD }} | base64`" >> $GITHUB_OUTPUT
