name: Check deploy comment

on:
  workflow_call:
    #inputs:
    outputs:
      PULL_REQUEST_REF:
        description: "the pr content"
        value: ${{ jobs.get-pr-info.outputs.pull_request_ref }}
    #secrets:
#env:

jobs:
  make-response:
    runs-on: self-hosted
    steps:
      - name: acknowledge deployment request to commenter
        id: check
        uses: khan/pull-request-comment-trigger@master
        with:
          trigger: "/deploy"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}

  get-pr-info:
    needs: make-response
    runs-on: self-hosted
    outputs:
      pull_request_ref: ${{ steps.get_pull_request_ref.outputs.data }}
    if: needs.make-response.outputs.triggered == 'true'
    steps:
      - name: Get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:issue_id
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Shows PR information
        run: |
          echo Head Ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
        shell: bash
